### ISSUE TITLE
"Export not found" errors?

### ISSUE THREAD

**Issue by phyllisstein** [faceyspacey/require-universal-module#4]
👋 Hey there! I was wondering if you could say anything about the circumstances under which you'd expect an "Export not found" error to be thrown when using this package in conjunction with `react-universal-component`.

All I can tell after about a day of troubleshooting is that the module it's being passed seems to be empty---it's just an object that looks like `{ __esModule: true }`---even though the module I'm `import`ing exports a React component and the file in which it's output appears in the correct order in the DOM. (I.e., the bootstrap chunk shows up first, then this module's chunk, then the main chunk.) I also know that visiting the page works fine if I load another page first and then navigate to it using React Router and the HTM5 history API, but fails when I try to load the page directly from an isomorphic rendering.

I'm sorry to ask such a vague question, but I'm at my wits' end---the whole shebang was working beautifully till just this morning, and I'm not sure what-all I did to break it. There might be a `git bisect` in my future.

**Comment by faceyspacey** [comment]
can you paste me some culprit code real quick. and if i cant see the problem, we'll move to a quick throwaway repo. I probably can though.

**Comment by faceyspacey** [comment]
also feel free to post early. These things are getting a great response, but it's still new that I don't have that many issues to deal with. I rather be able to resolve things quickly and be able to keep everyone happy :)

**Comment by phyllisstein** [comment]
😃 Thanks, I appreciate that! It turned out (thanks, `git bisect`!) to be an issue with Webpack's `CommonsChunkPlugin`. Changing an async/all-children commons chunk's `minChunks` from `6` to `3` somehow caused it to choke:

```diff
diff --git a/config/lib/build-webpack-config.js b/config/lib/build-webpack-config.js
index c629eab..84bfe15 100644
--- a/config/lib/build-webpack-config.js
+++ b/config/lib/build-webpack-config.js
@@ -100,7 +100,7 @@ export default function buildWebpackConfig(args) {
             new webpack.optimize.CommonsChunkPlugin({
                 async: true,
                 children: true,
-                minChunks: 6,
+                minChunks: 3,
             }),
         ]
     }
```

Disabling the `async` option seems to have solved the problem, even with the smaller `minChunks`:

```diff
diff --git a/config/lib/build-webpack-config.js b/config/lib/build-webpack-config.js
index f2e9134..f41b344 100644
--- a/config/lib/build-webpack-config.js
+++ b/config/lib/build-webpack-config.js
@@ -99,7 +99,6 @@ export default function buildWebpackConfig(args) {
         browserPlugins = [
             ...browserPlugins,
             new webpack.optimize.CommonsChunkPlugin({
-                async: true,
                 children: true,
                 minChunks: 3,
             }),
```

I suspect the underlying issue may have been with the Extract Text plugin, as I've seen it choke on commons chunks before, but it's hard to know for sure and I can't find the GitHub issues about its `async` woes. Happy to send you an invitation to the repo if you'd like to poke around in it and investigate further.

**Comment by faceyspacey** [comment]
i've never used it and i struggle to figure out its use-case, but the `async` option seems to create another chunk that u simply didnt have embedded on the page. 

If that's the case and if ur using `webpack-flush-chunks` and know it's name (which u can in fact set by doing `async: 'async-common-chunk'`), u can just add it to the end of the `before` array (one of the options to `flushChunks`)--if u still want to use the `async` option. 

I've never used this option, but I assume the idea is that your dynamic async chunks may have common code that your named entry bundles don't have, and you want to provide this additional common chunk only under the circumstances that ur loading a dynamic chunk. lol

it's all good on the repo. but let me know if u try a named `async` chunk, let me know so i'm aware for future users.

**Comment by faceyspacey** [comment]
check the latest docs if u havent already:

https://webpack.js.org/plugins/commons-chunk-plugin/

**Comment by faceyspacey** [comment]
...also it seems the reason it did not work before with `minChunks: 3`, where it worked with `minChunks: 6` is that ur module wasn't moved to the async chunk (which was never included). 

so once u brought the config down to a minimum of 3 chunks (u must have had at least 3 dynamic chunks importing it), the plugin moved it to an *async-commons* chunk.

**Comment by phyllisstein** [comment]
That all makes sense. Giving the commons chunk a name and forcibly flushing it is clever, but I suspect it defeats the purpose of making it async. My lay understanding, based on the docs and a little experimentation, is that an async chunk is meant to cut down on the page's initial loading and parsing time by being pulled in after Webpack boots and while other dependencies are loading. Not super clear on it myself---which means who gives a heck, no harm no foul. 😉 

Thanks again for giving this some thought! Glad to have it all working again.
